language: node_js

node_js:
  - "stable"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo apt-get install imagemagick ghostscript poppler-utils

before_script:
  - npm link
