language: node_js

node_js:
  - "stable"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install imagemagick ghostscript poppler-utils
  - wget -O "Raleway.zip" "https://fonts.google.com/download?family=Raleway"
  - sudo unzip -u "Raleway.zip" -d /root/.fonts

before_script:
  - npm link
